# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128)),
                ('complete', models.BooleanField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
